version: "3.7"

services:

  node-red:
    container_name: node-red
    build:
      context: .
      dockerfile: ./nodered-core.Dockerfile
    ports:
      - "1880:1880"
    environment:
      - NODE_RED_ENABLE_SAFE_MODE=false
      - TZ=Europe/Moscow
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red:/data 
    restart: always

  node-red-w1:
    container_name: node-red-w1
    build:
      context: .
      dockerfile: ./nodered-core.Dockerfile
    ports:
      - "1882:1882"
    environment:
      - NODE_RED_ENABLE_SAFE_MODE=true
      - TZ=Europe/Moscow
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red-w1:/data 
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass Yz25RAdGgkFg
    ports:
     - "6379:6379"
    environment:
         - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - tibotnet


volumes:
  redis-data:

networks:
  tibotnet: